# Generated by Django 5.0.2 on 2024-02-16 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha Registro')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Fecha Creacion')),
                ('date_updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Actualizacion')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Edad')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Sueldo')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cvitae', models.FileField(blank=True, null=True, upload_to='cvitae/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['id'],
            },
        ),
    ]
